server:
  servlet:
    content-path: /demo
  tomcat:
    uri-encoding: UTF-8
  port: 8082
spring:
  datasource:
    # 驱动配置信息
    url: jdbc:mysql://47.98.131.13/first_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池的配置信息
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 0
    database: 0
  mybatis:
    type-aliases-package: com.example.demo.*.domain
    mapper-location: classpath*:mapper/**/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: true
  pagehelper:
    helper-dialet: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  sys:
    # swagger
    swaggerEnable: true
    jwtTimeOut: 86400000ms
    redisTimeOut: 86400000ms
  #文件上传
  #upload:
    #url: C://Users\
#logging:
#  config: classpath:logback-spring.xml
#  level:
#    dao: debug
#    org:
#      mybatis: debug
